exclude: ^tests/data/
repos:
  - repo: https://github.com/pre-commit/pre-commit
    rev: v4.0.0
    hooks:
      - id: validate_manifest
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
  - repo: https://gitee.com/openmmlab/mirrors-isort
    rev: 5.11.5
    hooks:
      - id: isort
  - repo: https://gitee.com/openmmlab/mirrors-yapf
    rev: v0.32.0
    hooks:
      - id: yapf
  - repo: https://gitee.com/openmmlab/mirrors-pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: ["--remove"]
      - id: mixed-line-ending
        args: ["--fix=lf"]
  - repo: https://gitee.com/openmmlab/mirrors-mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-openmmlab
          - mdformat_frontmatter
          - linkify-it-py
  - repo: https://gitee.com/openmmlab/mirrors-codespell
    rev: v2.2.1
    hooks:
      - id: codespell
  - repo: https://gitee.com/openmmlab/mirrors-docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ["--in-place", "--wrap-descriptions", "79"]
  - repo: https://gitee.com/openmmlab/mirrors-pyupgrade
    rev: v3.0.0
    hooks:
      - id: pyupgrade
        args: ["--py36-plus"]
  - repo: https://gitee.com/openmmlab/pre-commit-hooks
    rev: v0.4.0
    hooks:
      - id: check-copyright
        args: ["mmengine", "tests"]
      - id: remove-improper-eol-in-cn-docs
  - repo: https://gitee.com/openmmlab/mirrors-mypy
    rev: v1.2.0
    hooks:
      - id: mypy
        exclude: |-
          (?x)(
              ^examples
              | ^docs
          )
        additional_dependencies: ["types-setuptools", "types-requests", "types-PyYAML"]
