version: 2

formats:
    - epub

sphinx:
  configuration: docs/zh_cn/conf.py

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements/runtime.txt
    - requirements: requirements/docs.txt
    - requirements: requirements/docs_extra.txt
